extends Node

# Brief overview of what your mod does...

# ! Comments prefixed with "!" mean they are extra info. Comments without them
# ! should be kept because they give your mod structure and make it easier to
# ! read by other modders


const MOD_DIR = "Roadbobek-CustomMenu/" # name of the folder that this file is in
const MYMOD_LOG = "Roadbobek-CustomMenu" # full ID of your mod (AuthorName-ModName)

var dir = ""
var ext_dir = ""


func _init(modLoader = ModLoader):
    # ModLoaderUtils.log_info("Init", MYMOD_LOG) # bradar wat is this?
    ModLoaderLog.info("Init", MYMOD_LOG)

    # ! We can't use `ModLoader` because the ModLoader instance isn't available
    # ! at this point in the mod's loading process. Instead, the class instance
    # ! is passed to a mod's `_init` func via the variable `modLoader`.
    # ! It will be available in any other places in your mod though, such as in
    # ! your _ready func.
    #!!!!!!!!!!!!!!!dir = ModLoaderMod.get_unpacked_dir() + MOD_DIR
    # Old n broken: 
    # dir = modLoader.UNPACKED_DIR + MOD_DIR
    #!!!!!!!!!!!!!!!ext_dir = dir + "extensions/" # ! any script extensions should go in this folder, and should follow the same folder structure as vanilla
    
    # Add extensions
    #!!!!!!!!!!!!!!!!!!!!ModLoaderMod.install_script_extension(ext_dir + "main.gd") # brief description of this edit...
    # Old n broken: 
    # modLoader.install_script_extension(ext_dir + "main.gd") # brief description of this edit...
    # modLoader.install_script_extension(ext_dir + "entities/units/player/player.gd") # ! Note that this file does not exist in this example mod

    # ! Add extensions (longform version of the above)
    #modLoader.install_script_extension("res://mods-unpacked/AuthorName-ModName/extensions/main.gd")
    #modLoader.install_script_extension("res://mods-unpacked/AuthorName-ModName/extensions/entities/units/player/player.gd")

    # Add translations
    # ! Load translations for your mod, if you need them.
    # ! Add translations by adding a CSV called "modname.csv" into the "translations" folder.
    # ! Godot will automatically generate a ".translation" file, eg "modname.en.translation".
    # ! Note that in this example, only the file called "modname.csv" is custom;
    # ! any other files in the "translations" folder were automatically generated by Godot
    #modLoader.add_translation_from_resource(dir + "translations/modname.en.translation")


func _ready()->void:
    ModLoaderLog.info("Ready", MYMOD_LOG)
    
    # ! This uses Godot's native `tr` func, which translates a string. You'll
    # ! find this particular string in the example CSV here: translations/modname.csv
    #ModLoaderLog.info(str("Translation Demo: ", tr("MODNAME_READY_TEXT")), MYMOD_LOG)
    
    
    
    
    ## 1. Define the path to your extra script
    #var extra_script_path = ModLoaderMod.get_unpacked_dir() + MOD_DIR + "extensions/main.gd"
    #
    ## 2. Check if it exists, then load it
    #if FileAccess.file_exists(extra_script_path):
        #var script = load(extra_script_path)
        #var script_instance = Node.new() # Create a blank node
        #script_instance.set_script(script) # Attach your script to it
        #script_instance.name = "MyModLogic"
        #
        #add_child(script_instance) # Add it to the scene tree so its _ready() runs
        #ModLoaderLog.info("Successfully loaded extra script manually: " + extra_script_path, MYMOD_LOG)
    #else:
        #ModLoaderLog.error("Could not find script at: " + extra_script_path, MYMOD_LOG)
        
        
        
    
    
    var main_menu = get_tree().root.find_child("Menu", true, false)
    
    if main_menu:
        var custom_menu = load(ModLoaderMod.get_unpacked_dir() + MOD_DIR + "extensions/menu_roadbobek.tscn").instantiate()
        
        # Loop to grab every child in your container, we dont need to since we just have one Control node as child...
        for child in custom_menu.get_children():
             # Remove from container first so Godot doesn't complain about double-parenting
             custom_menu.remove_child(child) 
             # Add it to the real game menu
             main_menu.add_child(child)
             # Move just above bg img
             main_menu.move_child(child, 2)

        ModLoaderLog.info("Successfully injected custom nodes into the menu.", MYMOD_LOG)
    
    else:
        ModLoaderLog.error("Could not find the Menu node!", MYMOD_LOG)
